### ISSUE TITLE
New Zealand dataset should be replaced with a more meaningful dataset

### ISSUE THREAD

**Issue by dokempf** [ssciwr/afwizard#220]
Preferrably of some archaeologic relevance.

**Comment by zaw-shinoto** [comment]
I am working on the Nakadake data set (nkd-W_02PC8404_ept_1-1-0-0.laz), a 200m*200m section from Gokuyama. 

We may call this **Nakadake-Gokuyama**. 

As discussed yesterday, I am aiming at 1.5million points and .laz format with few MB size; an irregular polygon may give a more significant selection with less data volume. 

Furthermore, I can add several segmentation suggestions in GeoJSON.

**Comment by zaw-shinoto** [comment]
Data set will be published under https://doi.org/10.11588/data/TJNQZG with heidata.
